project_id = "nuslehifiiopxqggsejl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "dual"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"
s3_credentials_access_key_id = "env(SUPABASE_ACCESS_KEY_ID)"
s3_credentials_secret_access_key = "env(SUPABASE_SECRET_ACCESS_KEY)"
s3_region = "local"
s3_bucket = "stub"
s3_endpoint = "http://127.0.0.1:54324/storage/v1/s3"

[auth]
enabled = true
api_url = "http://127.0.0.1:54321"
api_key = "env(SUPABASE_ANON_KEY)"
dashboard_url = "http://127.0.0.1:54324"
redirect_urls = ["https://127.0.0.1:3000/**"]
jwt_secret = "env(SUPABASE_JWT_SECRET)"
password_length = 6
password_requirements = "letters,numbers"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_SECRET)"

[edge_runtime]
enabled = true
port = 54329
inspector_port = 8083

[functions.ai-financial-agent]
verify_jwt = false

[functions.ai-investment-analysis]
verify_jwt = false

[functions.deposits]
verify_jwt = false

[functions.market-analysis]
verify_jwt = false

[functions.mubasher-scraper]
verify_jwt = false

[functions.personalized-news-agent]
verify_jwt = false

[functions.ai-router-agent]
verify_jwt = false

[functions.test-google-search]
verify_jwt = false

[functions.egyptian-market-news]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false