// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuslehifiiopxqggsejl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51c2xlaGlmaWlvcHhxZ2dzZWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Mjk2NzksImV4cCI6MjA2OTAwNTY3OX0.RIIVNszOSW-23_71Pft_muIl7x_afYfD3SrKJ2Ypad8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});